# Generated by Django 3.2.4 on 2021-06-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('salutation', models.CharField(blank=True, max_length=3, null=True)),
                ('date_created', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=3, null=True)),
                ('date_created', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.merchant')),
            ],
        ),
    ]
