# Generated by Django 3.2.4 on 2021-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20210625_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='salutation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
