# Generated by Django 3.2.4 on 2021-06-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
